import URL, { pathname_get as URL_pathname_get, pathname_set as URL_pathname_set } from "std:global/URL";
import Set, { size_get as Set_size_get } from "std:global/Set";
import { apply as Reflect_apply } from "std:global/Reflect";
const arr = [1, 2, 3];
arr.length = 5;
const b = arr.length;
const u = new URL();
const c = Reflect_apply(URL_pathname_get, u) && 5;
Reflect_apply(URL_pathname_set, u, [b]);
const s = new Set(arr);
const d = Reflect_apply(Set_size_get, s);
