import Document, { createElement as Document_createElement, body_get as Document_body_get } from "std:global/Document";
import URL, { pathname_get as URL_pathname_get } from "std:global/URL";
import String from "std:global/String";
import { setAttribute as Element_setAttribute, getAttribute as Element_getAttribute, querySelector as Element_querySelector } from "std:global/Element";
import { apply as Reflect_apply } from "std:global/Reflect";
import { document_get as Window_document_get } from "std:global/Window";
const d = new Document();
Reflect_apply(Element_setAttribute, Reflect_apply(Document_createElement, d, ['div']), ['background-color', 'blue']);
Reflect_apply(Element_getAttribute, Reflect_apply(Document_createElement, d, ['div']), ['background-color']).length;
const url = new URL();
Reflect_apply(URL_pathname_get, url).length;
Reflect_apply(Element_querySelector, Reflect_apply(Document_body_get, Window_document_get()), ['class']);
const n = new Document(new String());
